name: projet_steam
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_html: ^3.0.0
  go_router: ^14.8.1
  xml: ^6.5.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - res/svg/